### ISSUE TITLE
example-01-http doesn't work on Windows

### ISSUE THREAD

**Issue by velkyel** [bkaradzic/bnet#18]
Example always fails on ConnectFailed.  Especially connectsocket() returns -1:
https://github.com/bkaradzic/bnet/blob/master/src/bnet.cpp#L125

It's 64bit build without ssl.  On linux and osx it works fine.

**Comment by bkaradzic** [comment]
Interesting, failure is due to MS redefining `EWOULDBLOCK` to something else, in their new ucrt library.
